function htmlout = string2html(inputstr,varargin)
bgcolor = get_varargin(varargin,'bgcolor','white');
fontsize = get_varargin(varargin,'fontsize',4);
fontcolor = get_varargin(varargin,'fontcolor','black');
fontname = get_varargin(varargin,'fontname','Arial');
useicon = get_varargin(varargin,'icon','');
if strcmpi(useicon,'')
    htmlout=[sprintf('<html>'),...
        sprintf('<div style="width: 1080px; background-color:%s; color:%s ">',bgcolor,fontcolor),...
        sprintf('<font face=%s size=%d> %s </font>',fontname,fontsize,inputstr),...
        sprintf('</div>'),...
        sprintf('</html>')];
else
    htmlout=[sprintf('<html>'),...
        sprintf('<div style="width: 1080px; background-color:%s; color:%s ">',bgcolor,fontcolor),...
        sprintf('<img src="file:/%s" height=%d width=%d>',useicon,16,16),...
        sprintf('&nbsp'),...
        sprintf('<font face=%s size=%d> %s </font>',fontname,fontsize,inputstr),...
        sprintf('</div>'),...
        sprintf('</html>')];
end